networks:
  ms-network:
    driver: bridge

services:
  ms1-app:
    build: ../../proyecto-cloud-ms1
    container_name: ms1-app
    ports:
      - "8081:8081"
    env_file:
      - ./ms1.env
    networks:
      - ms-network
    restart: unless-stopped

  ms2-app:
    build: ../../proyecto-cloud-ms2
    container_name: ms2-app
    ports:
      - "8082:8000"
    env_file:
      - ./ms2.env
    networks:
      - ms-network
    restart: unless-stopped

  ms3-app:
    build: ../../proyecto-cloud-ms3
    container_name: ms3-app
    ports:
      - "8083:3000"
    env_file:
      - ./ms3.env
    networks:
      - ms-network
    depends_on:
      - ms1-app
      - ms2-app
    restart: unless-stopped

  ms4-app:
    build: ../../proyecto-cloud-ms4
    container_name: ms4-app
    ports:
      - "8084:8000"
    env_file:
      - ./ms4.env
    networks:
      - ms-network
    depends_on:
      - ms1-app
      - ms2-app
      - ms3-app
    restart: unless-stopped

  ms5-app:
    build: ../../proyecto-cloud-ms5/api
    container_name: ms5-app
    ports:
      - "8085:8000"
    env_file:
      - ./ms5.env
    networks:
      - ms-network
    restart: unless-stopped